version: '3.9'

networks:
  proxy:
    name: proxy
    external: true
  workspace:
    name: workspace
    external: true

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
      - PHP_OPCACHE_INTERNED_STRINGS_BUFFER=16
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_FPM_TYPE=ondemand
      - PHP_FPM_MAX_CHILDREN=100
      - PHP_FPM_MAX_REQUESTS=1000
    restart: always
    pull_policy: always
    networks:
      - workspace
      - proxy
    volumes:
      - ./:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.tgatubot.rule=HostRegexp(`{host:(^tgatubot.+)}`)
      - traefik.http.services.tgatubot.loadbalancer.server.port=80
