name: Deploy
on:
  - workflow_dispatch

env:
  PHP_REPO: ghcr.io/${{ github.repository }}
  GIT_USER: faceoffdev

jobs:
  web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: $GIT_USER
          password: ${{ secrets.GH_TOKEN }}
      - name: Get Build Information
        id: build_info
        run: |
          echo "::set-output name=version_tag::${GITHUB_REF/refs\/tags\/v/}"
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.PHP_REPO }}/web-app:latest
